### ISSUE TITLE
Recognize indentation

### ISSUE THREAD

**Issue by iinfin** [Tyriar/vscode-sort-lines#39]
Is it possible to recognize indentation and keep indented lines attached to parents?

like from
```
ccc
bbb
    a fff
    a eee
```
to
```
bbb
    a eee
    a fff
ccc
```

instead of throwing e and f to beginning because of "a". First sorting as blocks, then sorting sub-lines in each block.

**Comment by Tyriar** [comment]
@iinfin I don't understand the example, can you provide more details? Even ignoring whitespace the "to" example is in a strange order.

**Comment by iinfin** [comment]
@Tyriar I didn't mean ignoring whitespace, lines starting with "`a`" have indentation so they're the child of "`b`", they stay under it. And get sorted in their own scope.

Thought would be useful for cases like markdown lists.

**Comment by Tyriar** [comment]
Oh I get it, I think that's a little out of the scope of this extension unfortunately. Supporting every single possible way of sorting is unfeasible imo and makes the extension hard to use, that's what I'm trying to solve with the https://github.com/Tyriar/vscode-sort-lines/issues/40 issue. Perhaps there's a way to make sorts defined in settings somehow aware of other items? https://github.com/Tyriar/vscode-sort-lines/issues/40

**Comment by lioneltrebuchon** [comment]
Hello!

I understand this thread is closed, but I have a differing opinion from the boss (respect and greetings to you) @Tyriar .

Indeed, the use case of sorting multilevel/indented lists is to be found across the board... Many people look for it in Google Docs, MS Word, Sublime, Atom (there are questions about that on each one's forums, and stackoverflow)... 

The fact that this feature is longed for also in non-coding environments shows that it is of use in many, language agnostic, cases: when people want to create a visual dictionnary, when they want to define a multilevel list without yet defining the format (be it json, md, python dicts etc...), when they have several classes in Python defining several variables, when they want to make a dependency list in a comment/header (of a function in ANY language) that should be read by Doxygen, Sphynx etc...

For most of those use cases, sorting would be an important step, and then one can always decorate, comment out etc... later. But keeping the indentation, and sorting according to it, would be great.

Conclusion:
Listing by indentation seems a common way of defining hiearchy. It is, to a certain extent, language agnostic.
Because it is visually useful to humans, and we are the ones coding after all. 
Sorting with awareness of this way of defining hierarchy would be useful in many usecases.

**Comment by sparr** [comment]
I am looking for this feature for sorting structured data like ini, json, yaml, etc files.
